STYLEDOCDIR_LOCAL = $(STYLEDOCDIR)/util

compile:
	$(MAKE) -C threads

clean:
	$(MAKE) -C threads clean

style:
	$(MAKE) STYLEDOCDIR=$(STYLEDOCDIR_LOCAL) -C threads style


indent:
	$(MAKE) -C threads indent
