STYLEDOCDIR_LOCAL = $(STYLEDOCDIR)/remote

compile:
	$(MAKE) -C callback $(MAKE_PARAMS)
	$(MAKE) -C server $(MAKE_PARAMS)

clean:
	$(MAKE) -C callback $(MAKE_PARAMS) clean
	$(MAKE) -C server $(MAKE_PARAMS) clean

style:
	$(MAKE) STYLEDOCDIR=$(STYLEDOCDIR_LOCAL) -C callback $(MAKE_PARAMS) style
	$(MAKE) STYLEDOCDIR=$(STYLEDOCDIR_LOCAL) -C server $(MAKE_PARAMS) style


indent:
	$(MAKE) -C callback $(MAKE_PARAMS) indent
	$(MAKE) -C server $(MAKE_PARAMS) indent
