STYLEDOCDIR_LOCAL = $(STYLEDOCDIR)/callback

compile:
	$(MAKE) -C xmlrpc $(MAKE_PARAMS)

clean:
	$(MAKE) -C xmlrpc $(MAKE_PARAMS) clean

style:
	$(MAKE) STYLEDOCDIR=$(STYLEDOCDIR_LOCAL) -C xmlrpc $(MAKE_PARAMS) style

indent:
	find ./ -maxdepth 1 | grep \\.[ch]$$ | grep -v docs/ | xargs indent
	$(MAKE) -C xmlrpc $(MAKE_PARAMS) indent
