STYLEDOCDIR_LOCAL = $(STYLEDOCDIR)/sipstack

compile:
	$(MAKE) -C eXosip

clean:
	$(MAKE) -C eXosip clean

style:
	$(MAKE) STYLEDOCDIR=$(STYLEDOCDIR_LOCAL) -C eXosip style


indent:
	$(MAKE) -C eXosip indent
