STYLEDOCDIR_LOCAL = $(STYLEDOCDIR)/config

compile:
	$(MAKE) -C xml $(MAKE_PARAMS)

clean:
	$(MAKE) -C xml $(MAKE_PARAMS) clean

style:
	$(MAKE) STYLEDOCDIR=$(STYLEDOCDIR_LOCAL) -C xml $(MAKE_PARAMS) style

indent:
	find ./ -maxdepth 1 | grep \\.[ch]$$ | grep -v docs/ | xargs indent
	$(MAKE) -C xml $(MAKE_PARAMS) indent
