#ifndef HEVENTS_USED
#    define HEVENTS_USED

typedef enum {
    INVALID_EVENT,
    GUI_MAKE_CALL,
    GUI_END_CALL,
    GUI_ACCEPT_CALL,
    SIPLISTENER_INCOMING_CALL,
    SIPLISTENER_CANCEL_CALL,
    SIPLISTENER_QUIT_CALL,
    SIPLISTENER_DECLINE_CALL,
    SIPLISTENER_THROW,
    SIPLISTENER_CONNECT_CALL
} event;

#endif
