STYLEDOCDIR_LOCAL = $(STYLEDOCDIR)/sipstack

compile:
	$(MAKE) -C eXosip $(MAKE_PARAMS)
	
clean:
	$(MAKE) -C eXosip $(MAKE_PARAMS) clean

check: compile

style:
	$(MAKE) STYLEDOCDIR=$(STYLEDOCDIR_LOCAL) -C eXosip $(MAKE_PARAMS) style

indent:
	find ./ -maxdepth 1 | grep \\.[ch]$$ | grep -v docs/ | xargs indent
	$(MAKE) -C eXosip $(MAKE_PARAMS) indent
